version: '3.9'

services:
  web:
    build: .
    container_name: kallpa_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/kallpa_db
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: kallpa_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kallpa_db
    ports:
      - "5432:5432"
    volumes:
      - kallpa_pgdata:/var/lib/postgresql/data

volumes:
  kallpa_pgdata: